// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebPuntoVenta.Data.Models;

public partial class Categorias
{
    public int Id { get; set; }

    public string Categoria { get; set; }

    public int? IdPadre { get; set; }

    public virtual Categorias IdPadreNavigation { get; set; }

    public virtual ICollection<Categorias> InverseIdPadreNavigation { get; set; } = new List<Categorias>();

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}