// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebPuntoVenta.Data.Models;

public partial class CodigosPostales
{
    public int Id { get; set; }

    public int IdMunicipio { get; set; }

    public int CodigoPostal { get; set; }

    public string Asentamiento { get; set; }

    public virtual ICollection<Direcciones> Direcciones { get; set; } = new List<Direcciones>();

    public virtual Municipios IdMunicipioNavigation { get; set; }
}