// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebPuntoVenta.Data.Models;

public partial class Estados
{
    public int Id { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Municipios> Municipios { get; set; } = new List<Municipios>();
}