// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebPuntoVenta.Data.Models;

public partial class Municipios
{
    public int Id { get; set; }

    public int IdEstado { get; set; }

    public byte Cve { get; set; }

    public string Municipio { get; set; }

    public virtual ICollection<CodigosPostales> CodigosPostales { get; set; } = new List<CodigosPostales>();

    public virtual Estados IdEstadoNavigation { get; set; }
}