// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebPuntoVenta.Data.Models;

public partial class Ocasiones
{
    public int Id { get; set; }

    public string Ocasion { get; set; }

    public virtual ICollection<ProductoOcasiones> ProductoOcasiones { get; set; } = new List<ProductoOcasiones>();
}