// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace WebPuntoVenta.Data.Models;

public partial class ProductoOcasiones
{
    public int Id { get; set; }

    public int IdProducto { get; set; }

    public int IdOcasion { get; set; }

    public virtual Ocasiones IdOcasionNavigation { get; set; }

    public virtual Productos IdProductoNavigation { get; set; }
}